### PR TITLE
[12.0][FIX] Fix the full update of an organization

### PR DESCRIPTION
**Pull request by foutoucour**
Someone out of an organization cannot have access to its team list

ss

### CODE REVIEW

**Review by legalsylvain — CHANGES_REQUESTED** [review]
Hi,
If user doesnt' have correct access right, it should raise an error.
With your proposal, user will not have information if it fails.
If not full access, others buttons are available to specific actions.

**Comment by foutoucour** [comment]
Hey @legalsylvain 
thank you for the feedback.
Just to be sure, the fix only affect the cronjob or the manual execution of the cronjob.
There is still an error raised if an user updates the list of team in the Github interface:
MuK IT - Odoo - Mozilla Firefox (20200304_1021)

Do you think we need to raise an error in the interface in the case of the cronjob ?

**Comment by pedrobaeza** [comment]
@legalsylvain any further comment?

**Review by houssine78 — APPROVED** [review]

**Comment by legalsylvain** [comment]
> @legalsylvain any further comment?

no sorry. I abstain on that point. I'm currently not use this module. (I developped it for the OCA). 

thanks for maintaining it.

**Pull request closed without merging**
