### PR TITLE
15.0 mig GitHub connector

### PR DESCRIPTION
**Pull request by OpenCode**

### CODE REVIEW

**Comment by OpenCode** [comment]
@OCA/community-maintainers Any suggestion about the missing depends error in pre-commit?
`Missing external dependency "github.GithubException" from manifest.`
The external dependency is in the manifest. The library is PyGithub.

**Comment by pedrobaeza** [comment]
Please include #85

**Comment by OpenCode** [comment]
> Please include #85

I can track the change in an issue and I can apply it after the merge of this PR because the PR #85 includes a module from another PR.

**Comment by OpenCode** [comment]
https://github.com/OCA/interface-github/issues/86

**Review by victoralmau — CHANGES_REQUESTED** [review]
Thanks, some comments:
- Include https://github.com/OCA/interface-github/pull/85 to commit history.
- Changes from commit "correct pylint checks" add them to commit "Migration to 15.0"
- Squash administrative commits.

**Comment by victoralmau** [comment]
Please include https://github.com/OCA/interface-github/pull/87

**Comment by victoralmau** [comment]
Superseed by https://github.com/OCA/interface-github/pull/90

**Pull request closed without merging**
