### PR TITLE
[12.0][IMP] github_connector: Added the SOURCE_CODE_LOCAL_PATH environment variable

### PR DESCRIPTION
**Pull request by imanie383**
[12.0][IMP] github_connector: Added the SOURCE_CODE_LOCAL_PATH environment variable

backport: https://github.com/OCA/interface-github/pull/57

### CODE REVIEW

**Comment by pedrobaeza** [comment]
Please check #57 for the solution taken in 13.0

**Comment by imanie383** [comment]
> Please check #57 for the solution taken in 13.0

Done @pedrobaeza

**Comment by hugho-ad** [comment]
@imanie383 
did you made the cherry-pick?

LGMT :+1:

**Comment by imanie383** [comment]
> @imanie383
> did you made the cherry-pick?
> 
> LGMT

Yes i did

**Review by moylop260 — APPROVED** [review]
👍

**Comment by moylop260** [comment]
/ocabot merge minor

Since that it is a valid backport merged from https://github.com/OCA/interface-github/pull/57

**Pull request merged**
