### PR TITLE
[ADD] Missed dependency on README

### PR DESCRIPTION
**Pull request by Shide**
Missed dependency on README

### CODE REVIEW

**Comment by rafaelbn** [comment]
@legalsylvain please could verify? Thank you!

**Review by legalsylvain — APPROVED** [review]
Thanks

**Review by rafaelbn — APPROVED** [review]
Super 👍

**Comment by pedrobaeza** [comment]
There's a merge commit in the PR. Please rebase and remove it.

**Comment by Shide** [comment]
@pedrobaeza Ya he squasheado los commits

**Pull request merged**
