### PR TITLE
15.0 mig GitHub connector odoo

### PR DESCRIPTION
**Pull request by OpenCode**
Need https://github.com/OCA/interface-github/pull/83

### CODE REVIEW

**Comment by pedrobaeza** [comment]
Please include #85

**Comment by OpenCode** [comment]
> Please include #85

I can track the change in an issue and I can apply it after the merge of this PR because the PR #85 includes a module from another PR.

**Comment by OpenCode** [comment]
https://github.com/OCA/interface-github/issues/86

**Comment by pedrobaeza** [comment]
The PR is merged, so you can just repeat the procedure of extracting the commit history, and put on top your changes.

**Comment by victoralmau** [comment]
Please include https://github.com/OCA/interface-github/pull/64

**Review by victoralmau — CHANGES_REQUESTED** [review]
Thanks, some comments:
- Include https://github.com/OCA/interface-github/pull/85 to commit history.
- Changes from commit "correct pylint checks" add them to commit "Migration to 15.0"
- Squash administrative commits.

**Comment by victoralmau** [comment]
Please include https://github.com/OCA/interface-github/pull/87

**Comment by OpenCode** [comment]
> The PR is merged, so you can just repeat the procedure of extracting the commit history, and put on top your changes.

If I try to apply git format-patch + git am command, every file have a conflict. There is particular step to follow?

**Comment by victoralmau** [comment]
> > The PR is merged, so you can just repeat the procedure of extracting the commit history, and put on top your changes.
> 
> If I try to apply git format-patch + git am command, every file have a conflict. There is particular step to follow?

This would be the same as indicated in https://github.com/OCA/interface-github/pull/84#issuecomment-1176399005

**Comment by OpenCode** [comment]
> > > The PR is merged, so you can just repeat the procedure of extracting the commit history, and put on top your changes.
> > 
> > 
> > If I try to apply git format-patch + git am command, every file have a conflict. There is particular step to follow?
> 
> This would be the same as indicated in [#84 (comment)](https://github.com/OCA/interface-github/pull/84#issuecomment-1176399005)

I've done it. And after the step with git format-patch + git am I have the conflicts.

**Comment by victoralmau** [comment]
Superseed by https://github.com/OCA/interface-github/pull/97

**Pull request closed without merging**
