### PR TITLE
[14.0][FIX] github_connector_*, fix smart button open actions

### PR DESCRIPTION
**Pull request by GSLabIt**

### CODE REVIEW

**Review by pedrobaeza — APPROVED** [review]

**Comment by GSLabIt** [comment]
@pedrobaeza it seems odoo broke something in permission for action, this is the nth case it's needed the fix. 

Have you more infos?

**Comment by pedrobaeza** [comment]
It's an intended change, and included in the migration guide:

https://github.com/OCA/maintainer-tools/wiki/Migration-to-version-14.0

(the point `The access to ir.actions.* objects...`)

**Comment by pedrobaeza** [comment]
Fast-tracking this as straight-forward:

/ocabot merge patch

**Comment by GSLabIt** [comment]
> It's an intended change, and included in the migration guide:
> 
> https://github.com/OCA/maintainer-tools/wiki/Migration-to-version-14.0
> 
> (the point `The access to ir.actions.* objects...`)

Thanks for the hint, i noticed they changed code using the model instead:

`action = self.env["ir.actions.actions"]._for_xml_id("external_id")`

https://github.com/odoo/odoo/blob/a7f7233e0eae8ee101d745a9813cba930fd03dcb/addons/sale_crm/models/crm_lead.py#L42

to keep in mind 😅

**Pull request merged**
