### PR TITLE
[15.0][IMP] github_connector*: Skip analysis rule info lines without info

### PR DESCRIPTION
**Pull request by victoralmau**
Depends on:

- [x] #107

Do not create lines if no file has been scanned

@Tecnativa

### CODE REVIEW

**Comment by pedrobaeza** [comment]
Will this remove the existing 0 lines?

**Comment by victoralmau** [comment]
> Will this remove the existing 0 lines?

This would prevent new lines with 0 from being created.
I will add a small migration script to remove existing lines with 0.

**Review by legalsylvain — APPROVED** [review]
thanks. make sense !

**Review by pedrobaeza — APPROVED** [review]
/ocabot merge patch

**Pull request merged**
