### PR TITLE
[FIX] github_connector: remove duplicated group

### PR DESCRIPTION
**Pull request by cubells**
cc @Tecnativa

### CODE REVIEW

**Comment by pedrobaeza** [comment]
Why do you remove it?

**Comment by cubells** [comment]
Because in migration pr (https://github.com/OCA/interface-github/pull/10) I move res_groups file to data as Elicoidal recommends me (https://github.com/OCA/interface-github/pull/10/files#diff-9ea9830efdcac4e57642740ae1af729b), but I forgot to remove old file.

**Comment by pedrobaeza** [comment]
Well, it should be the contrary. This should be in security, not in data.

**Comment by cubells** [comment]
So now It's time to do the right thing :nerd_face: 

https://github.com/OCA/interface-github/pull/10#discussion_r192553356

**Comment by cubells** [comment]
Sorry @pedrobaeza 

the problem is that the group is repeated:
https://github.com/OCA/interface-github/blob/11.0/github_connector/data/res_groups.xml#L13
and
https://github.com/OCA/interface-github/blob/11.0/github_connector/security/res_groups.xml#L9

I think I must delete data file and restore security file. What do you think?

**Comment by pedrobaeza** [comment]
Yes, this kind of change should be in security folder, not in data. Check why Travis is red and runbot is red.

**Review by pedrobaeza — APPROVED** [review]

**Pull request merged**
