### PR TITLE
[IMP] Set a default icon per module

### PR DESCRIPTION
**Pull request by StephanRozendaal**
Change includes:
 - Set a default icon per Odoo module

### CODE REVIEW

**Review by elicoidal — APPROVED** [review]
LGTM.
Version number

**Review by legalsylvain — CHANGES_REQUESTED** [review]
Hi, As the module github_connector_odoo can fetch many repositories, I think this proposal is not very extendable because we can fetch many organization with that module. (Specially if we are integrators, we can fetch our repositories, and the OCA repository).

I'd prefer to add on the organization, a new field name default_odoo_image, that would be used if no image are found. What do you think ? 
if yes, you could move the current oca.png image in the demo data.

regards

**Comment by StephanRozendaal** [comment]
@legalsylvain : Thanks for you comments.

I agree with your proposal, It's better if we make it configurable.
I can pick this up in the coming days.
Regards,

**Comment by elicoidal** [comment]
@legalsylvain Agree!

**Comment by bizzappdev** [comment]
@StephanRozendaal @legalsylvain  we can also use the Image of the Organization. 
selection_213

**Comment by pedrobaeza** [comment]
Merged for not getting the problem. @sbidoul please deploy also this one.

**Comment by sbidoul** [comment]
It's deployed.

**Pull request merged**
