### PR TITLE
[15.0][MIG] github_connector: Migration to 15.0

### PR DESCRIPTION
**Pull request by victoralmau**
Superseed https://github.com/OCA/interface-github/pull/83

Migration to 15.0

Please @pedrobaeza and @CarlosRoca13 can you review it?

@Tecnativa TT40167

### CODE REVIEW

**Review by CarlosRoca13 — APPROVED** [review]

**Comment by pedrobaeza** [comment]
Please squash together both migration commits (lint + migration). Did you make changes? They should be in a separate commit.

**Comment by victoralmau** [comment]
Changes done (it seems that github does not work updating commits). There is a separate migration commit with my changes.

**Comment by victoralmau** [comment]
Merged commits into one.

Applied rebase + added changes from https://github.com/OCA/interface-github/pull/94 in commit history.

Pre-commit error is related to https://github.com/OCA/oca-addons-repo-template/pull/170.

**Review by pedrobaeza — APPROVED** [review]

**Pull request merged**
