### PR TITLE
[15.0][MIG] github_connector_oca

### PR DESCRIPTION
**Pull request by hhgabelgaard**
Std. migrations

### CODE REVIEW

**Review by legalsylvain — APPROVED** [review]

**Comment by pedrobaeza** [comment]
Tests are red

**Comment by hhgabelgaard** [comment]
I belive this error:
2023-03-23 15:04:46,854 240 CRITICAL ? odoo.modules.module: module 'lib' has no attribute 'X509_V_FLAG_CB_ISSUER_CHECK'

Is due to an incompability between pyopenssl 19.0 and cryptography in a "too new version" (i.e newer than 3.4.8)
But is this in the CI image or where to fix ?

**Review by Tardo — APPROVED** [review]
Thanks for the work! 
Code review.

**Pull request closed without merging**
