### PR TITLE
[15.0][IMP] github_connector_odoo: Add maintainers

### PR DESCRIPTION
**Pull request by victoralmau**
Add maintainers

Please @pedrobaeza can you review it?

@Tecnativa TT48258

### CODE REVIEW

**Comment by pedrobaeza** [comment]
Please do this directly in 16

**Review by legalsylvain — APPROVED** [review]
Nice addition ! 

code review / No test.

**Review by pedrobaeza — CHANGES_REQUESTED** [review]
I don't think this requires an extra model that bloats up the DB (model, views, security...).

Just a string containing the elements separated by comma is enough IMO. There's not going to have extra information attached to each maintainer AFAIK. And you can search for the maintainer in the string directly.

**Comment by legalsylvain** [comment]
> Just a string containing the elements separated by comma is enough IMO. 

Hum not so simple. Having a dedicated table allow more information, better statistic, etc...
In the other hand, the github_connector base module add a github login on res_partner so, maybe this information is redondant, and module should be associated to partners in a new field maintainer_ids = field.Many2many(comodel_name="res.partner")

**Comment by pedrobaeza** [comment]
All that "future" things may come later, but for now, having an extra model with all its burden is too much IMO, and for our use case, which is the important thing, it's enough.

About using github users, better not, as that means that you should have them populated and that they actually exists (which can't be the case due to old alias, typos, etc).

**Comment by victoralmau** [comment]
Changes done.

**Review by pedrobaeza — APPROVED** [review]
As a first step, this is OK. If we need something more sophisticated, it can be changed later.

/ocabot merge minor

**Pull request merged**
