### PR TITLE
[IMP] Add try-except on branch analyze action

### PR DESCRIPTION
**Pull request by StephanRozendaal**
Change includes: 
 - Add try-except statements on analyze actions that could potentially crash the analyze process.

### CODE REVIEW

**Comment by RoelAdriaans** [comment]
Review request @oscarolar @bizzappdev
cc @elicoidal

**Review by bizzappdev — APPROVED** [review]
LGTM

**Review by oscarolar — APPROVED** [review]
LGTM

**Comment by bizzappdev** [comment]
@elicoidal  Can you please take care for merging?

**Review by elicoidal — APPROVED** [review]
LGTM.
Version number

**Pull request merged**
