### PR TITLE
[12.0][IMP] github_connector_odoo: Preventing the crash if some arguments are not passed

### PR DESCRIPTION
**Pull request by imanie383**
[IMP] github_connector_odoo: Preventing the crash if some arguments are not passed like in data demo

https://runbot.odoo-community.org/runbot/static/build/3435040-59-9aed61/logs/job_20_test_all.txt

backport: https://github.com/OCA/interface-github/commit/c9d48191805dd09262e1aeb94b9247487105607d

### CODE REVIEW

**Comment by imanie383** [comment]
@Yajo can you check this?

**Review by hugho-ad — APPROVED** [review]

**Comment by hugho-ad** [comment]
@moylop260

could you review this, pls?

**Review by moylop260 — APPROVED** [review]
It looks like a valid change
Since that it is a backport from 13.0 of 
https://github.com/OCA/interface-github/pull/56

**Pull request merged**
