### PR TITLE
[IMP] github connector: All modules only can be access by github app …

### PR DESCRIPTION
**Pull request by hugho-ad**
…user

### CODE REVIEW

**Comment by hugho-ad** [comment]
@oscarolar 

please review

**Comment by hugho-ad** [comment]
@pedrobaeza 

could you review this please

**Comment by pedrobaeza** [comment]
Why creating a new group instead of putting them to existing group?

**Comment by hugho-ad** [comment]
in order to keep settings visible only to GitHub connector manager

**Comment by pedrobaeza** [comment]
But I don't see the role of GitHub user against the manager...

Any way, please put this green

**Comment by hugho-ad** [comment]
Done.

I kept it simple, Just all github app menus under a github user, except settings menu,

I didn't apply user group to models, because website_app_store use them on the website shop,

**Review by pedrobaeza — APPROVED** [review]
OK, let's allow this

**Comment by hugho-ad** [comment]
@cubells  do you main review this please

**Review by cubells — APPROVED** [review]
:+1: 

LGTM

Code review and test

**Pull request merged**
