### PR TITLE
[16.0][MIG] github_connector_odoo: Migration to version 16.0

### PR DESCRIPTION
**Pull request by carolinafernandez-tecnativa**
- Standard migration to v16

TT45634
@Tecnativa

@pedrobaeza @victoralmau

### CODE REVIEW

**Comment by pedrobaeza** [comment]
Please rebase fixing conflicts.

/ocabot migration github_connector_odoo

**Comment by carolinafernandez-tecnativa** [comment]
> Please rebase fixing conflicts.
> 
> /ocabot migration github_connector_odoo

done!

**Review by victoralmau — APPROVED** [review]
Code and functional review OK

**Review by pedrobaeza — APPROVED** [review]
/ocabot merge nobump

**Pull request merged**
