### PR TITLE
[MIG] github_connector_odoo: Migration to 11.0

### PR DESCRIPTION
**Pull request by cubells**
Depends on:
- [x] https://github.com/OCA/interface-github/pull/10
cc @Tecnativa

### CODE REVIEW

**Comment by pedrobaeza** [comment]
Please rebase

**Comment by pedrobaeza** [comment]
I don't know why runbot fails, but it should be a glitch due to the rebase.

**Comment by moylop260** [comment]
FYI runbot fails because of the dependency module is not available for this branch:
 - https://github.com/Tecnativa/interface-github/tree/2dea355239c54493e2b1f27d82d50032cd7690ce

I just used the feature of ssh connection to docker container:

 - screen shot 2018-06-05 at 09 23 41

It is because runbot use the branch without changes.
Travis is green because use a merge with the base.

**Comment by pedrobaeza** [comment]
OK, then the rebase is not correct. Thanks for the info. @cubells please rebase properly.

**Comment by pedrobaeza** [comment]
Is there any documentation about how to connect by SSH to the runbot instance?

**Comment by moylop260** [comment]
There is not documentation real we just have a thread about:
 - [Connection to runbot build using ssh to debug](https://odoo-community.org/groups/contributors-15/contributors-61007)

 - pedro

**Comment by pedrobaeza** [comment]
Oh, it's already there in contributing.md:

https://github.com/OCA/maintainer-tools/blob/master/CONTRIBUTING.md#investigating-travis-test-failures

I have to remember that...

**Comment by cubells** [comment]
@pedrobaeza rebased!

**Comment by moylop260** [comment]
@cubells before rebase use fetch then rebase and verify that you have the other module in your folders
Maybe a git clean could be helpful for you too

**Comment by pedrobaeza** [comment]
@cubells , this is the usual stuff:
```
git fetch origin
git rebase origin/11.0
```
please check what are you doing wrong.

**Comment by cubells** [comment]
now it's correctly done.

**Review by pedrobaeza — APPROVED** [review]

**Pull request merged**
